module.exports = {
  MESSAGE: {
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
  },
  USER: {
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    USER_DRAG: "USER_DRAG",
    USER_LIST: "USER_LIST",
    USER_LOGOUT: "USER_LOGOUT",
    USER_TYPING: "USER_TYPING",
    USER_VERIFY : "USER_VERIFY",
  },
};