module.exports = {
  MESSAGE: {
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SEND: "MESSAGE_SEND",
  },
  USER: {
    USER_CONNECT: "connection",
    USER_CONNECTED: "USER_CONNECTED",
    USER_JOIN_ROOM: "USER_JOIN_ROOM",
    USER_DISCONNECT: "disconnect",
    USER_MOVE: "USER_MOVE",
    USER_LIST: "USER_LIST",
    USER_LOGOUT: "USER_LOGOUT",
    USER_TYPING: "USER_TYPING",
    USER_VERIFY : "USER_VERIFY",
  },
};